### ISSUE TITLE
Local import paths

### ISSUE THREAD

**Issue by christophberger** [Vladimir37/Backlun#15]
The import paths in Backlun.go (and possibly in other files as well, I did not look further) are local. 

Suggestion: Change the imports to include the GitHub path (e.g., `import "github.com/Vladimir37/Backlun/back/blackjack"`) to make the project `go get`table. 

(BTW, building from a downloaded zip file, as advised in the readme, is not an option. Unzipping the files somewhere and running `go build` fails because Go searches the import paths relative to `$GOPATH/src`. Even unzipping into `$GOPATH/src` would not help, as the top-level folder in the zip file is named "Backlun-master" where `go build` would expect it to be just "Backlun".

EDIT: And `go get` would also fetch all dependencies, like e.g. `github.com/Pallinder/go-randomdata". `go build` doesn't do this but simply errors out.)

**Comment by Vladimir37** [comment]
Thank you! I'll fix it soon.

**Comment by asm-jaime** [comment]
Ok, I fixed it. #18

**Comment by Vladimir37** [comment]
Fixed, release builds are updated.
