### ISSUE TITLE
Why no CORS middleware in gin server settings ?

### ISSUE THREAD

**Issue by erklat** [Vladimir37/Backlun#16]
Hello, you have created this for frontend developers such as myself so that we do not
have the hassle of finding or making api to try new frontend stuff, but you forgot to 
include Allow-origin header, so when I try to make ajax call to your server I get CORS error. I see where  you make new server instance on back/blog/server.go and after that only include middleware for handling different origin access, I would try doing myself if I had go environment set up, but I don't work in go. Please fix asap. Thx.

**Comment by asm-jaime** [comment]
@erklat hello. Do you have cors problem with geopos? (I will fix it).

**Comment by Vladimir37** [comment]
Fixed. Release builds, Readme and documentation are updated.
